export const assets = {
  logo: "/assets/logo-groov.svg",
  stars: "/assets/5-stars.svg",
  apple: "/assets/apple-icon.svg",
  check: "/assets/check-icon.svg",
  quotation: "/assets/quotation-mark.svg",
  nfl: "/assets/nfl-logo.svg",
  playVideo: "/assets/play-video.svg",
  trusters: "/assets/trusters.png",
  verified: "/assets/verified.svg",
  arrowFilled: "/assets/arrow-filled.svg",
  arrowLeft: "/assets/arrow-left.svg",
  arrowRight: "/assets/arrow-right.svg",
  heroClouds: "/assets/hero-v1.png",
  heroCloudsInsole: "/assets/hero-v1.insole.png",
  ctaDesktopBg: "/assets/bg-cta-desktop.png",
  ctaMobileBg: "/assets/bg-cta-mobile.png",
  ctaInsoleFloat1: "/assets/insole-float-1.png",
  ctaInsoleFloat2: "/assets/insole-float-2.png",
  teamsBg: "/assets/bg-teams.png",
  teamsInsole: "/assets/insole-animation.png",
  navigationProducts: [
    {
      name: "The Response",
      price: "$149",
      tag: "Plush",
      image: "/assets/navigation/menu.everyday.png",
      tagIcon: "/assets/navigation/plush.png",
    },
    {
      name: "The Luxe",
      price: "$149",
      tag: "Elegant",
      image: "/assets/navigation/menu.theluxe.png",
      tagIcon: "/assets/navigation/elegant.png",
    },
    {
      name: "The Blade",
      price: "$149",
      tag: "Game-Ready",
      image: "/assets/navigation/menu.theblade.png",
      tagIcon: "/assets/navigation/game-ready.png",
    },
    {
      name: "The Response",
      price: "$149",
      tag: "Sleek",
      image: "/assets/navigation/menu.response.png",
      tagIcon: "/assets/navigation/sleek.png",
    },
  ],
  heroCards: [
    "/assets/image-card-4.png",
    "/assets/image-card-3.png",
    "/assets/image-card-2.png",
    "/assets/image-card-1.png",
  ],
  scrollModels: [
    "/assets/scroll-everyday.png",
    "/assets/scroll-response.png",
    "/assets/scroll-luxe.png",
    "/assets/scroll-blade.png",
  ],
  trustedLogos: [
    { name: "St. Louis Cardinals", image: "/assets/trusted-team.svg", className: "max-h-14 max-w-[92px] opacity-35 grayscale" },
    { name: "FC Dallas", image: "/assets/trusted-fc-dallas.svg", className: "max-h-14 max-w-[92px] opacity-55 grayscale" },
    { name: "NFLPA", image: "/assets/trusted-nflpa.svg", className: "max-h-14 max-w-[150px] opacity-60 grayscale" },
    { name: "Hospital for Special Surgery", image: "/assets/trusted-hospital.svg", className: "max-h-14 max-w-[220px] opacity-60 grayscale" },
    { name: "MyGolfSpy", image: "/assets/trusted-mygolf.svg", className: "max-h-14 max-w-[210px] opacity-55 grayscale" },
  ],
  videoTestimonials: [
    {
      name: "Von Miller",
      handle: "@vonmiller",
      meta: "2M followers &bull; Super Bowl MVP",
      quote: "Groov turned my least favorite shoes into my favorite shoes... and my favorite shoes into my favorite favorite shoes.",
      image: "/assets/von-miller.png",
      badge: "/assets/nfl-logo.svg",
    },
    {
      name: "Dr. Krista Archer, DPM",
      handle: "Dr. Krista Archer, DPM",
      meta: "Board-Certified Podiatrist, New York City",
      quote: "Scan your feet with your iPhone for freedom from foot pain",
      image: "/assets/dra-krista.png",
    },
  ],
  favoriteShoeCards: [
    { image: "/assets/card.1.png", alt: "Runner wearing Groov in a desert landscape" },
    { image: "/assets/card.2.png", alt: "Groov insoles with white socks" },
    { image: "/assets/card.3.png", alt: "Groov insole held over a handbag" },
    { image: "/assets/card.4.png", alt: "Groov lifestyle editorial card" },
  ],
  socialProofArrows: {
    left: "/assets/social-proof/left-arrow.svg",
    right: "/assets/social-proof/right-arrow.svg",
  },
  socialProofPlay: "/assets/social-proof/play-video-2.svg",
  socialProofFastCompany: "/assets/social-proof/fast-company.svg",
  socialProofItems: [
    {
      type: "video",
      image: "/assets/social-proof/1.png",
      alt: "Dr. Krista Archer portrait",
      quote: '"Between efficacy and efficiency, Groov is a game-changer for any practice."',
      name: "Dr. Krista Archer",
      role: "Board-Certified Podiatrist, New York City",
    },
    {
      type: "video",
      image: "/assets/social-proof/2.png",
      alt: "Customer holding Groov insoles",
      name: "@aaron",
      meta: "27k followers",
    },
    {
      type: "photo",
      image: "/assets/social-proof/3.png",
      alt: "Portrait of @baldynfl",
      quote: '"I have foot problems...but not with Groovs in my shoes. These things are like limousines for my feet."',
      name: "@baldynfl",
      meta: "2M followers",
    },
    {
      type: "video",
      image: "/assets/social-proof/4.png",
      alt: "Maurice Allen portrait",
      quote: `"I just keep saying it's dope. You can create complex designs very easily."`,
      name: "Maurice Allen",
      role: "Long Drive Golf World Champion",
      meta: "126k followers",
    },
    {
      type: "press",
      image: "/assets/social-proof/5.png",
      alt: "Fast Company social proof card",
      quoteBefore: '"Groov says its ',
      quoteEmphasis: "high-precision foot scanning",
      quoteAfter: ` app can bring custom shoe insoles out of the doctor's office"`,
    },
  ],
  modelCards: [
    {
      name: "The Luxe",
      image: "/assets/model-the-luxe.png",
      description: "Designed for heels, flats, boots, and dress shoe.",
    },
    {
      name: "The Everyday",
      image: "/assets/model-the-everyday.png",
      description: "Designed for everyday movement.",
      selected: true,
    },
    {
      name: "The Response",
      image: "/assets/model-the-response.png",
      description: "Designed for athletic performance.",
    },
    {
      name: "The Blade",
      image: "/assets/model-the-blade.png",
      description: "Designed specifically for ice skates.",
    },
  ],
  step2: "/assets/step-2.png",
};

export const scrollModels = [
  {
    name: "The Everyday",
    title: "The Everyday, by Groov",
    subtitle: "Plush. Cushy. A hug for your feet.",
    image: "/assets/scroll-everyday.png",
    video: "/assets/video-scroll/everyday.mp4",
    duration: 5000,
  },
  {
    name: "The Response",
    title: "The Response, by Groov",
    subtitle: "Sleek. Fast. Ready for blast-off.",
    image: "/assets/scroll-response.png",
    duration: 5000,
  },
  {
    name: "The Luxe",
    title: "The Luxe, by Groov",
    subtitle: "Elegant. Compact. Perfect for snug shoes.",
    image: "/assets/scroll-luxe.png",
    duration: 5000,
  },
  {
    name: "The Blade",
    title: "The Blade, by Groov",
    subtitle: "Honed. Balanced. Engineered for On-Ice Precision.",
    image: "/assets/scroll-blade.png",
    video: "/assets/video-scroll/the-blade.mp4",
    duration: 5000,
  },
];
